name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Image Tag to Deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-specifications/*
